version: '3'

services:
  spring-session-redis:
    build: redis
    ports: 
      - 6379:6379
  spring-session-1:
    build: .
    ports: 
      - 8081:8080
    environment:
      - APPLICATION_TITLE=First instance
    depends_on:
      - "spring-session-redis"
  spring-session-2:
    build: .
    ports: 
      - 8082:8080
    environment:
      - APPLICATION_TITLE=Second instance
    depends_on:
      - "spring-session-redis"    
  spring-session-nginx:
    build: nginx
    ports: 
      - 8080:80
    depends_on:
      - "spring-session-1"
      - "spring-session-2"